name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  win-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: numworks/setup-msys2@v1
        with:
          msystem: MINGW32
      - run: msys2do pacman --noconfirm --needed -S base-devel mingw-w64-i686-toolchain mingw-w64-i686-geos
      - run: msys2do ./build.sh
      - uses: actions/upload-artifact@v1
        with:
          name: win-x86
          path: artifacts
  win-x64:
    needs: win-x86
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: numworks/setup-msys2@v1
      - run: msys2do pacman --noconfirm --needed -S base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-geos
      - run: msys2do ./build.sh
      - uses: actions/download-artifact@v1
        with:
          name: win-x86
          path: artifacts
      - run: ./pack.cmd
      - uses: actions/upload-artifact@v1
        with:
          name: packages
          path: artifacts/packages
      - run: ./test.cmd
